blockwork-eda/blockwork

blockwork/activities/bootstrap.py, blockwork/bootstrap/__init__.py, blockwork/bootstrap/registry.py, example/infra/bootstrap/tools.py
Fix indexing of bootstrap steps.
Add a bootstrap `mode` argument to allow forced rebuilds.
This was made a choice rather than a flag so that we can add more modes later, e.g. dryrun perhaps
=> Fix index and add mode flag for bootstrap

blockwork/containers/common.py, blockwork/containers/container.py
`bw build sim -t block` wasn't outputting correctly because an internal tool was outputting a weird character causing a decode error that then caused the entire line to be ignored
=> escape unicode errors and fix lack of carraige returns

blockwork/containers/container.py
Docker tmpfs mounts add a `noexec` flag to mounts by default, this means it's not possible to execute a binary from `/tmp`. This is fixed by switching to an anonymous volume.
=> Fixing 'noexec' flag on '/tmp'

blockwork/containers/container.py
Was getting 
```
Internal Server Error ("b'mount denied:\nthe source path "/tmp"\ndoesn\'t  contains colon'")
```
Changed according to:
https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run
=> Fix /tmp volume param when creating containers

blockwork/activities/tools.py, blockwork/build/transform.py, blockwork/tools/tool.py, example/infra/tools/compilers.py, example/infra/transforms/lint.py, example/infra/transforms/templating.py, tests/test_tools.py
Moved context pass-through for actions from the action call to get_action...
perhaps later this should be moved to the tool instantiation?
=> Pass through context to transforms

blockwork/activities/build.py, blockwork/build/execute.py
* `--interactive` - forces all invocations to run interactively;
* `--pre-shell` - launches a shell before an invocation starts;
* `--post-shell` - launches a shell after an invocation starts.
=> Adding '--pre-shell', '--post-shell', and '--interactive' options to 'bw build'

blockwork/containers/container.py
[https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size)
This should fix inappropriate ioctl errors when not on a terminal
=> use shutil get term size as it has fallback

blockwork/activities/workflow.py, blockwork/config/base.py, blockwork/config/config.py, blockwork/config/parser.py, blockwork/workflows/workflow.py, example/bench/testbench.yaml, example/design/top/design.yaml, example/infra/config/config.py, example/infra/transforms/lint.py, example/infra/transforms/templating.py, example/infra/workflows/lint.py, example/projects/example.yaml
Lots of configuration infra to link paths output from transforms to paths input into other transforms and config values
This is not used yet but is a stepping stone to getting workflows working properly.
The next thing will be to extend the `config.Linker` to calculate dependencies between transforms (most of the way there) and then we can run the transforms in order (until later when we need to deal with parallelism and it gets a bit more complicated)
=> Add dependency functionality to config (#31)

blockwork/bootstrap/tools.py
Helps when no "in-container" steps are required
=> Allowing null invocations from installer actions

blockwork/activities/info.py, blockwork/bootstrap/tools.py
* Tweaks the date comparison to examine the touch date on the install directory compared with the definition file, rather than using the `last_run` date;
* Use `os.utime(...)` to 'touch' the install directory to ensure datestamp is updated;
* Added blockwork install location to `bw info` to make it easier to locate.
=> Less Eager Tool Re-installs

blockwork/bootstrap/tools.py, blockwork/config/blockwork.py, blockwork/context.py, blockwork/foundation.py, blockwork/tools/tool.py, docs/config/bw_yaml.md, docs/syntax/tools.md, example/infra/tools/common.py, example/infra/tools/compilers.py, example/infra/tools/misc.py, example/infra/tools/simulators.py, example/infra/tools/wave_viewers.py, tests/test_tools.py
* `Tool.HOST_ROOT` introduced
* `Tool.ROOT` renamed to `Tool.CNTR_ROOT`
* `!Blockwork` config gains `tools:` and `host_tools:` elements
* Functions for path resolution based on `Tool.HOST_ROOT` and `Tool.CNTR_ROOT` are added to `Version`
* Example updated to adopt these variables
=> Adding Tool.HOST_ROOT to standardise locating tool installs

blockwork/build/interface.py, blockwork/build/transform.py, blockwork/common/checkeddataclasses.py, blockwork/config/base.py, blockwork/config/parser.py
Pass context through to interface resolvers
Catch and discard a noisy warning from typeguard
Improve how config is picked up from the command line
=> Misc fixes from real world use

blockwork/__main__.py, blockwork/activities/__init__.py, blockwork/activities/workflow.py, blockwork/build/interface.py, blockwork/build/transform.py, blockwork/common/complexnamespaces.py, blockwork/common/inithooks.py, blockwork/workflows/workflow.py, example/infra/workflows.py
Make wf a click command group so that workflows can set their own options
These are passed back through the transform filter so workflows can do their own filtering
Added *_interfaces properties which return namespaces to transform to make access a little nicer from user code. In particular for if these are used to filter transforms
Added some QOL keys/values/items methods to complexnamespaces
=> Make wf a command group and add example subcommand

blockwork/containers/container.py
Seems this is the "correct" way even though it isn't documented anywhere really...
Without:
```
0:main $ bw wf lint -p ex -t top
[09:20:35] INFO     Running transform: <infra.transforms.templating.MakoTransform object at 0x104905410>                                                                                                                               
[09:20:36] INFO     Running transform: <infra.transforms.lint.VerilatorLintTransform object at 0x104905650>                                                                                                                            
\x9d%Error: /project/design/top/counter.sv:20:5: syntax error, unexpected end, expecting TYPE-IDENTIFIER
20 |     end
|     ^~~
%Error: Cannot continue
```
With:
``` …
```
=> fix docker stream read

blockwork/activities/tools.py, blockwork/bootstrap/tools.py, blockwork/common/complexnamespaces.py, blockwork/config/base.py, blockwork/containers/container.py, blockwork/tools/tool.py, blockwork/workflows/workflow.py, example/bench/test.yaml, example/infra/config/config.py, example/infra/workflows.py
Changes workflows quite a lot...
A workflow is now simply a command-wrapped function which takes some arguments and returns some configuration. 
The interesting bits where workflows select transforms from a config have now been moved into configuration itself - with configuration able to hierarchically select what to run.
Configuration can now implement the `transform_filter` and `config_filter` methods. 
As before, `transform_filter` is used to select the target transforms to run (with dependencies of them automatically added). However, this now functions hierarchically and is controlled by the `config_filter`.
The `config_filter` acts upon configuration under the current level, and determines whether the sub-config's transform filter is used, or the current level's transform filter.
=> Workflows as config

blockwork/build/interface.py, blockwork/build/transform.py, blockwork/workflows/workflow.py
When setting the dependencies between transforms we aren't currently unrolling meta interfaces, so dependencies do not get created
=> Fix meta interface dependencies

blockwork/activities/tools.py, blockwork/containers/container.py, blockwork/foundation.py, blockwork/tools/tool.py
Adds an option to invocations to determine whether args that look like host paths should be automatically mapped into the container. This can then be set when calling tools directly from the command line, or omitted if not.
=> Conditionally map host paths

blockwork/build/caching.py, blockwork/config/api.py, blockwork/context.py
All paths under a run will contain a shared timestamp. It is to the second which I think is adequate for now
=> Put timestamp in paths

blockwork/build/caching.py
Allow broken symlinks to exist in a cached directory and just roll into the hash
=> handle broken symlink in caching

blockwork/build/interface.py
Get the real path before mapping into container
=> handle symlinks in fileinterface

blockwork/bootstrap/tools.py, blockwork/tools/tool.py
While the idea of using touch files is good, having them in the tools directory causes problems if symlinks are used for tool installs
=> Moving tool touch files into the state directory

blockwork/common/checkeddataclasses.py, blockwork/config/base.py
`dataclass_transform` enables type checker to treat our `Config` class as a dataclass factory so that type hints work correctly on fields.
Without:
With:
=> Use dataclass_transform to provide better type hints

blockwork/bootstrap/containers.py, blockwork/config/api.py, blockwork/containers/container.py, blockwork/foundation.py, example/.bw.yaml, poetry.lock, pyproject.toml
A few tweaks to make it easier to manage distributed builds across a number of machines:
* Automatically building container image if it doesn't exist when an invocation is launched;
* Using target and project in the scratch path whenever possible;
* Adding date stamps to scratch paths when target and project not known to lower chance of a collision
=> Making distributed builds easier

blockwork/__main__.py, blockwork/build/caching.py, blockwork/context.py, blockwork/transforms/transform.py, blockwork/workflows/workflow.py, example/.bw.yaml, example/infra/caches.py, tests/test_workflow.py
Roll in a hash of imported python modules. Python file hashing is based on the AST, which means whitespace and comment changes won't be considered. 
Some limitations:
- Won't detect or consider changes to python library files, or compiled python
- Won't detect manual changes inside pip installed modules 
- Will detect when module versions are updated, or modules are added or removed - but coarsely, it won't consider if the changed modules are actually dependencies or not.
- Python imports outside of the top level (e.g. imported within transform functions) will not become part of the hash. 
> I can't think how to do this without adding a lot of complexity
- Breakpoints/user-interaction will not prevent caching. This means if you stop on a breakpoint in a transform and continue, the …
=> Improve caching - detect transform changes

blockwork/activities/workflow.py, blockwork/common/registry.py, blockwork/containerfiles/foundation/Containerfile_x86, blockwork/transforms/transform.py, blockwork/transforms/transforms/file.py, docs/syntax/transforms.md, example/infra/tools/compilers.py, example/infra/transforms/examples.py, example/infra/transforms/lint.py, example/infra/transforms/templating.py, tests/test_transforms.py, tests/test_workflow.py
This means:
- Intellisense picks up types correctly
- Execute can call other methods on the transform class
Also fix a couple of issues with x86 bootstrap
=> Use 'self' instead of 'iface' object to access transform interface values in execute

blockwork/build/caching.py
Caching the hashes makes a big difference to performance
Fetch value change allows more flexibility in the implementation of fetch_item (e.g. allowing symlinks)
=> Cache hashes

blockwork/tools/tool.py, blockwork/tools/tools/shell.py, docs/syntax/tools.md, example/infra/tools/compilers.py, example/infra/tools/misc.py, example/infra/tools/objstore.py, example/infra/tools/simulators.py, example/infra/tools/wave_viewers.py, tests/test_tools.py
We don't need to specify the tool name in the action decorator if we tag the methods and process on subclass init
=> Remove toolname from action decorator

blockwork/bootstrap/tools.py
A version which is specified but not installed as part of bootstrap isn't usable
If the other versions are installed then we can override to use different versions
=> Install all tool versions, not just the default

.github/workflows/ci.yml, blockwork/transforms/transform.py, blockwork/workflows/workflow.py, pyproject.toml
Allow transforms to define `tf_report` and `tf_cls_report` methods which are run on the host after all transforms have run.
This provides an opportunity for transforms to output important information to the user when running in parallel
Also pinned the runner version as the default changed:
https://github.com/actions/runner-images/issues/10636
=> Add reporting hooks for transforms

blockwork/__main__.py, blockwork/activities/__init__.py, blockwork/activities/cache.py, blockwork/activities/exec.py, blockwork/activities/tools.py, blockwork/activities/workflow.py, blockwork/bootstrap/tools.py, blockwork/build/caching.py, blockwork/config/__init__.py, blockwork/config/blockwork.py, blockwork/config/caching.py, blockwork/containers/__init__.py, blockwork/containers/common.py, blockwork/containers/container.py, blockwork/context.py, blockwork/foundation.py, blockwork/transforms/__init__.py, blockwork/transforms/transform.py, blockwork/workflows/workflow.py, docs/config/bw_yaml.md, docs/config/caching.md, docs/tech/caching.md, example/.bw.yaml, example/.caches.yaml, example/infra/caches.py, mkdocs.yml, pyproject.toml, tests/test_context.py, tests/test_workflow.py
Added the ability to configure caches through a configuration file.
Improved cache behaviour when multiple caches are present and now allow configuration of which caches are active. Added determinism checking for when objects have the same transform hash but different output hashes.
Added documentation on caches.
Documented further improvements in #136
=> Cache improvements, configuration, and docs
